### ISSUE TITLE
System.Null

### ISSUE THREAD

**Issue by eid129121** [noname0310/AdofaiBpmNormalizer#2]
![image](https://github.com/user-attachments/assets/cb9dde1f-b39c-477e-bf0e-12507193b2e5)
맵을 넣어도 버그가 ㅠㅠ

**Comment by noname0310** [comment]
자유각도 기능이 나오기전에 개발하였습니다.
 그 이후 버전에선 작동하지 않기에 사실상 현재는 사용할 수 없는 프로그램 입니다.
